# Generated by Django 3.2.8 on 2021-10-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_LPB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadossede',
            name='chamada',
            field=models.TextField(null=True, verbose_name='Chamada'),
        ),
    ]
