# Generated by Django 3.2.8 on 2021-10-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_LPB', '0003_auto_20211014_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadossede',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
